SELECT
	Filmes.Nome,
	Atores.PrimeiroNome,
	Atores.UltimoNome,
	ElencoFilme.Papel
FROM
	Filmes
-- JUNTAMOS ELENCOFILME COM A COLUNA ID DA TABELA FILMES E A COLUNA IDFILME DA TABELA ELENCOFILME
INNER JOIN ElencoFilme ON Filmes.Id = ElencoFilme.IdFilme
-- JUNTAMOS O RESULTADO DE ATORES USANDO A COLUNA IDATOR DE ELENCOFILME E A COLUNA ID DE ATORES
INNER JOIN Atores ON ElencoFilme.IdAtor = Atores.Id