SELECT
	Filmes.Nome,
	Generos.Genero
FROM
	Filmes
-- COMBINANDO AS TABELAS FILMES E FILMESGENEROS, USANDO A COLUNA ID DE FILMES E IDFILME DE FILMESGENEROS
INNER JOIN FilmesGenero ON Filmes.Id = FilmesGenero.IdFilme
-- COMBINANDO O RESULTADO DE GENEROS USANDO A COLUNA IDGENERO DE FILMESGENERO E A COLUNA ID DE GENEROS
INNER JOIN Generos ON FilmesGenero.IdGenero = Generos.Id