SELECT
	Ano, -- PRIMEIRO SELECIONAMOS A COLUNA QUE QUEREMOS AGRUPAR
	COUNT(*) Quantidade -- FAZEMOS A CONTAGEM DE CADA VALOR IGUAL
FROM Filmes -- DA TABELA...?
GROUP BY
	Ano -- AGRUPAMOS A COLUNA QUE SELECIONAMOS
ORDER BY
	Quantidade DESC -- ORDENAMOS PELA CONTAGEM